### ISSUE TITLE
TCG and more vga adapters support?

### ISSUE THREAD

**Issue by JustinJ553** [kjliew/qemu-3dfx#27] opened 2021-12-29 14:11 UTC
Ran into issues where my Windows XP became slower when using whpx & haxm, and got blackscreen when using vbemp NT at both VBE 3.0 and VBE 2.0 modes. I wish 3dfx passthrough would support TCG and more display adapters like VMWare SVGA II, and Cirrus

Edit: Accidentally closed it.

**Comment by kjliew** [comment] 2021-12-29 23:16
MESA GL/3Dfx Glide passthrough **has no binding or dependency** on the QEMU emulated display adapters. They are independent user-space DLLs similar to Voodoo1/2 add-in 3D adapter on real machine. They already work with any QEMU currently emulated VGA-compatible display adapters, such as `virtio-vga, cirrus-vga, qxl-vga or vmware`. They also work with TCG, you just don't get the same performance when an accelerator `kvm | whpx` is available. Use the 10X rule to estimate the CPU performance, for eg. 1 GHz host CPU is roughly equivalent to 100MHz CPU performance.

The problem is existing display driver support. Only VBEMP and Cirrus VGA have 8-bit color modes. QXL only has 16-bit and 32-bit color modes. VMware SVGA only has 32-bit color mode. Many old Win9X games require 8-bit/16-bit color modes for their DirectDraw 2D UI before the actual gameplay in Glide or Direct3D. Or, they may have Intro/FMV players that expect 8-bit color modes at the start of the game. Hence, the black screen when those failed.

You have to tell me the games you were trying. Many of them can be fixed by using WineD3D DirectDraw which provides 8-bit color modes emulation.

**Comment by kjliew** [comment] 2022-02-02 20:02
Closed

**Closed by kjliew** 2022-02-02 20:02 UTC
