### ISSUE TITLE
After accelerated apps close; screen goes grey. This persists between reboots. mesapt: DLL unloaded last message

### ISSUE THREAD

**Issue by Nislaco** [kjliew/qemu-3dfx#140] opened 2024-08-30 17:07 UTC
After initial setup when performing tests from Addons CD and OpenGl apps run successfully. However, after that app is closed screen is grey with no output until qemu is closed and reloaded.  This is using windows 98SE with box9x driver as per wiki and setup video from youtube. 

Logs screens shots and configs used posted below.

![image](https://github.com/user-attachments/assets/3cea4ca5-3fc1-4481-9dd6-37b70b168203)
![image](https://github.com/user-attachments/assets/73842254-1754-4ba6-88bc-d005650cf0a7)
![image](https://github.com/user-attachments/assets/8320224b-af8a-47d6-b0ee-fafd677765ab)
![image](https://github.com/user-attachments/assets/63eb34f2-1011-4e60-b338-11dcd38ef14a)

$ ./qemu-system-i386.exe -nodefaults -monitor none -rtc base=localtime,clock=vm,driftfix=none -L . -monitor stdio -cpu Conroe,+kvm_pv_unhalt,+kvm_pv_eoi,hv_spinlocks=0x1fff,hv_vapic,hv_time,hv_reset,hv_vpindex,hv_runtime,hv_relaxed,kvm=off,hv_vendor_id=amd,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true,hypervisor=off,+3dnow -m 256m,maxmem=256m -object memory-backend-ram,id=ram0,size=256m,prealloc=on,share=off,merge=off -machine pc,accel=whpx,kernel-irqchip=off,hpet=off,acpi=off,sata=off,usb=off,vmport=off,smbus=off,smm=off,memory-backend=ram0 -display sdl,gl=on -device VGA,id=video0,bus=pci.0 -audiodev id=sdl,driver=sdl -audiodev id=sdl,driver=sdl -device AC97,audiodev=sdl,bus=pci.0 -device piix4-ide,id=ide1,bus=pci.0 -netdev user,id=net0 -device pcnet,rombar=0,netdev=net0,bus=pci.0 -device ide-cd,bus=ide1.0,drive=disk6 -drive if=none,id=disk6,media=cdrom,file="$CD1" -device ide-cd,bus=ide1.0,drive=disk7 -drive if=none,id=disk7,media=cdrom,file="$CD4" -device lsi,bus=pci.0,id=scsi1 -device scsi-hd,bus=scsi1.0,drive=disk0 -drive if=none,id=disk0,media=disk,file="$HD1",cache=writethrough,media=disk,format=qcow2 -device scsi-cd,bus=scsi1.0,drive=disk1 -drive if=none,id=disk1,media=cdrom,file="$CD2" -device scsi-cd,bus=scsi1.0,drive=disk2 -drive if=none,id=disk2,media=cdrom,file="$CD3" -device scsi-cd,bus=scsi1.0,drive=disk3 -drive if=none,id=disk3,media=cdrom,file="$CD7" -fda "$FD2" -fdb "$FD5"  -boot a
WARNING: Image format was not specified for 'E:\OS-files\9x-test-sw\cregfix1.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
WARNING: Image format was not specified for 'e:\9x3dfxdrv.ima' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
Windows Hypervisor Platform accelerator is operational
QEMU 9.0.0 monitor - type 'help' for more information
(qemu) mesapt: DLL loaded
glcntx: ChoosePixelFormat() fmt 0x0e
glcntx: MESAGL window [native 00000000001807b2] ready
glcntx: PixFmt 0x14 nAux 4 nSamples 0 0
glcntx: SetPixelFormat() fmt 0x14 ret 1
mesapt: wglCreateContext cntx 0 curr 0
mesapt: wglMakeCurrent cntx 1 curr 0 lvl 0
mesapt: 348cfc1-10:30:37 May 29 2024 build WRAPGL32
mesapt: VertexArrayCache 32MB
mesapt: DispTimerSched 2000ms
mesapt: MappedBufferObject One-copy
mesapt: Guest GL Extensions pass-through for Year ALL Length ANY
mesapt: wglDeleteContext cntx 1 curr 1 lvl 0
mesapt: VertexArrayStats: elemMax 000000 vertexCache 0000
mesapt: MGLStats: fifo 0x0000a12 data 0x0000006
mesapt: DLL unloaded

--------------------------------------------------------
OpenGLide Log File
--------------------------------------------------------
***** OpenGLide xtra@366bff1 *****
--------------------------------------------------------
Date: 08/30/24
Time: 12:46:41
--------------------------------------------------------
--------------------------------------------------------
Clock Frequency: 3600.01 Mhz
--------------------------------------------------------
--------------------------------------------------------
Configuration file is OpenGLid.ini
--------------------------------------------------------
Wrapper Class Priority of 32
Wrapper Priority of 2
--------------------------------------------------------
Configuration file is OpenGLid.ini
--------------------------------------------------------
Time: 12:47:00
--------------------------------------------------------

Configuration File for OpenGLide

Info:
Priority goes from 0(HIGH) to 5(IDLE)
Output resolution: 0 = original, 1.0-16.0 = scale factor, >16 = fixed width (height calculated automatically)
Texture Memory goes from 2 to 32
Frame Buffer Memory goes from 2 to 16
All other fields are boolean with 1(TRUE) and 0(FALSE)

Version=xtra@366bff1

[Options]
WrapperPriority=2
CreateWindow=0
InitFullScreen=0
Resolution=0.0
FogEnable=1
EnableMipMaps=0
IgnorePaletteChange=0
Wrap565to5551=1
FramebufferSRGB=0
EnablePrecisionFix=1
EnableMultiTextureEXT=1
EnablePaletteEXT=1
EnableVertexArrayEXT=1
TextureMemorySize=16
FrameBufferMemorySize=8
SamplesMSAA=0
OverrideSync=0
Annotate=0
NoSplash=1

Processor	AMD Ryzen 7 3700X 8-Core Processor, 3600 Mhz, 8 Core(s), 16 Logical Processor(s)
Renderer : AMD Radeon RX 6750 XT [ 22 ]
Vendor   : ATI Technologies Inc. [ 22 ]
Version  : 4.6.0 Compatibility Profile Context 24.7.1.240711 [ 50 ]

Shading Language Version : 4.60 [ 5 ]

Total pixel formats 252

**Comment by kjliew** [comment] 2024-08-30 20:18
Need details on HOST OpenGL provider. Run `$ wine-get glinfo` and submit the prints. A description of system details can also be helpful, such as CPU and GPU configuration. Did you consistently reproduce this "grey" screen issue all the time?

**Comment by kjliew** [comment] 2024-08-30 23:07
Found the issue. Please remove `'-display sdl,gl=on'` from QEMU invocation. For QEMU binary package built to the standards of qemu-3dfx, SDL2 is the only supported UI. If you built your own QEMU featuring qemu-3dfx, then only specify `'-display sdl'` without the GL part for Windows VMs intended for qemu-3dfx usage.

**Comment by Nislaco** [comment] 2024-08-31 01:10
My apologies for misunderstanding that part. I did a quick test and confirmed that fixed the issue. Thank you.

**Comment by Nislaco** [comment] 2024-08-31 04:07
I do often utilize builds with qemu-3dfx built in as well as being a donor and having a prebuilt package.

I do use -display sdl,gl=on when using qemu-3dfx builds for Android and linux (debian/Ubuntu) guests on Windows 10/11. Should this be turned off for those guest OS if using the virgl/SDL patches?

Also would any of these settings cause issues and or need to be excluded when trying to use qemu-3dfx/virgl patches for mesa and modern Linux/Android guests:  

export QEMU_VIRTIO_GPU_DEBUG=1 ;
export LIBGL_DEBUG=verbose ;
export MESA_DEBUG=1 ;
export VIRGL_DEBUG=all ;
export GALLIUM_DRIVER=virgl ;
export SDL_VIDEO_DRIVER=windows ; 
export SDL_RENDER_DRIVER=opengl ;
export SDL_RENDER_SCALE_QUALITY=0 ;
export SDL_RENDER_VSYNC=0 ;
export GALLIUM_DRIVER=virgl
export MESA_GL_VERSION_OVERRIDE=4.0

**Comment by kjliew** [comment] 2024-08-31 21:17
> I do use -display sdl,gl=on when using qemu-3dfx builds for Android and linux (debian/Ubuntu) guests on Windows 10/11. Should this be turned off for those guest OS if using the virgl/SDL patches?

No. You can have `'display sdl,gl=on'` on VMs not expecting qemu-3dfx activation, such as Android/Linux guests, for having native Virgl support for 3D acceleration. For most common cases, Virgl and qemu-3dfx are mutually exclusive 3D acceleration schemes, unless someone happened to bring on Virgl into Win98/ME/2K/XP (a very welcome undertaking but extremely unlikely). Perhaps an unusual scenario might have been possible when Virgl on Windows finally landed and 32-bit x86 support wasn't broken for Windows 10, the last standing 32-bit Windows. Though unsupported and never meant to be, qemu-3dfx works in _ALL_ 32-bit Windows up to the latest Windows 10.

> export QEMU_VIRTIO_GPU_DEBUG=1 ; export LIBGL_DEBUG=verbose ; export MESA_DEBUG=1 ; export VIRGL_DEBUG=all ; export GALLIUM_DRIVER=virgl ; export SDL_VIDEO_DRIVER=windows ; export SDL_RENDER_DRIVER=opengl ; export SDL_RENDER_SCALE_QUALITY=0 ; export SDL_RENDER_VSYNC=0 ; export GALLIUM_DRIVER=virgl export MESA_GL_VERSION_OVERRIDE=4.0

I would suggest that you do away with these unnecessary ENV overrides except for the `*_DEBUG` and `*_OVERRIDE`, if and only if, you do really must have them. Many are already the rightful defaults anyway. Unnecessary ENV overrides can sometimes cause troubles, especially with the `SDL_*`. Just let SDL2 figure out what's best for itself.

**Comment by Nislaco** [comment] 2024-08-31 22:26
Thank you for the clarification, and assistance. To confirm removing "gl=on" clears up the issue on my end and apps load and unload without losing the screen output.

The only override I needed was when running qemu within a Hyper-V instance in which there is no OpenGL and I did have to set SDL to use directx11/12 instead. 

Personally, I would be happy with just the virtio disk drivers for win9x. But LSI /SCSI is pretty sweet. Working 1GB Ethernet would also be sweet for qemu and 9X.

**Closed** 2024-09-08 05:52 UTC
